#include <plug_common.h>

// virtual functions:

// void Awesomium::WebView::Destroy()
// Awesomium::WebViewType Awesomium::WebView::type()
// int Awesomium::WebView::process_id()
// ProcessHandle Awesomium::WebView::process_handle()
// void Awesomium::WebView::set_parent_window(NativeWindow parent)
// NativeWindow Awesomium::WebView::parent_window()
// NativeWindow Awesomium::WebView::window()
// void Awesomium::WebView::set_view_listener(WebViewListener::View * listener)
// void Awesomium::WebView::set_load_listener(WebViewListener::Load * listener)
// void Awesomium::WebView::set_process_listener(WebViewListener::Process * listener)
// void Awesomium::WebView::set_menu_listener(WebViewListener::Menu * listener)
// void Awesomium::WebView::set_dialog_listener(WebViewListener::Dialog * listener)
// void Awesomium::WebView::set_print_listener(WebViewListener::Print * listener)
// void Awesomium::WebView::set_download_listener(WebViewListener::Download * listener)
// void Awesomium::WebView::set_input_method_editor_listener(WebViewListener::InputMethodEditor * listener)
// WebViewListener::View * Awesomium::WebView::view_listener()
// WebViewListener::Load * Awesomium::WebView::load_listener()
// WebViewListener::Process * Awesomium::WebView::process_listener()
// WebViewListener::Menu * Awesomium::WebView::menu_listener()
// WebViewListener::Dialog * Awesomium::WebView::dialog_listener()
// WebViewListener::Print * Awesomium::WebView::print_listener()
// WebViewListener::Download * Awesomium::WebView::download_listener()
// WebViewListener::InputMethodEditor * Awesomium::WebView::input_method_editor_listener()
// void Awesomium::WebView::LoadURL(const Awesomium::WebURL & url)
// void Awesomium::WebView::GoBack()
// void Awesomium::WebView::GoForward()
// void Awesomium::WebView::GoToHistoryOffset(int offset)
// void Awesomium::WebView::Stop()
// void Awesomium::WebView::Reload(bool ignore_cache)
// bool Awesomium::WebView::CanGoBack()
// bool Awesomium::WebView::CanGoForward()
// Awesomium::Surface * Awesomium::WebView::surface()
// Awesomium::WebURL Awesomium::WebView::url()
// Awesomium::WebString Awesomium::WebView::title()
// Awesomium::WebSession * Awesomium::WebView::session()
// bool Awesomium::WebView::IsLoading()
// bool Awesomium::WebView::IsCrashed()
// void Awesomium::WebView::Resize(int width, int height)
// void Awesomium::WebView::SetTransparent(bool is_transparent)
// bool Awesomium::WebView::IsTransparent()
// void Awesomium::WebView::PauseRendering()
// void Awesomium::WebView::ResumeRendering()
// void Awesomium::WebView::Focus()
// void Awesomium::WebView::Unfocus()
// Awesomium::FocusedElementType Awesomium::WebView::focused_element_type()
// void Awesomium::WebView::InjectMouseMove(int x, int y)
// void Awesomium::WebView::InjectMouseDown(Awesomium::MouseButton button)
// void Awesomium::WebView::InjectMouseUp(Awesomium::MouseButton button)
// void Awesomium::WebView::InjectMouseWheel(int scroll_vert, int scroll_horz)
// void Awesomium::WebView::InjectKeyboardEvent(const Awesomium::WebKeyboardEvent & key_event)
// void Awesomium::WebView::InjectTouchEvent(const Awesomium::WebTouchEvent & touch_event)
// void Awesomium::WebView::ActivateIME(bool activate)
// void Awesomium::WebView::SetIMEComposition(const Awesomium::WebString & input_string, int cursor_pos, int target_start, int target_end)
// void Awesomium::WebView::ConfirmIMEComposition(const Awesomium::WebString & input_string)
// void Awesomium::WebView::CancelIMEComposition()
// void Awesomium::WebView::Undo()
// void Awesomium::WebView::Redo()
// void Awesomium::WebView::Cut()
// void Awesomium::WebView::Copy()
// void Awesomium::WebView::CopyImageAt(int x, int y)
// void Awesomium::WebView::Paste()
// void Awesomium::WebView::PasteAndMatchStyle()
// void Awesomium::WebView::SelectAll()
// int Awesomium::WebView::PrintToFile(const Awesomium::WebString & output_directory, const Awesomium::PrintConfig & config)
// Awesomium::Error Awesomium::WebView::last_error() const
// Awesomium::JSValue Awesomium::WebView::CreateGlobalJavascriptObject(const Awesomium::WebString & name)
// void Awesomium::WebView::ExecuteJavascript(const Awesomium::WebString & script, const Awesomium::WebString & frame_xpath)
// Awesomium::JSValue Awesomium::WebView::ExecuteJavascriptWithResult(const Awesomium::WebString & script, const Awesomium::WebString & frame_xpath)
// void Awesomium::WebView::set_js_method_handler(Awesomium::JSMethodHandler * handler)
// Awesomium::JSMethodHandler * Awesomium::WebView::js_method_handler()
// void Awesomium::WebView::DidSelectPopupMenuItem(int item_index)
// void Awesomium::WebView::DidCancelPopupMenu()
// void Awesomium::WebView::DidChooseFiles(const Awesomium::WebStringArray & files, bool should_write_files)
// void Awesomium::WebView::DidLogin(int request_id, const Awesomium::WebString & username, const Awesomium::WebString & password)
// void Awesomium::WebView::DidCancelLogin(int request_id)
// void Awesomium::WebView::DidChooseDownloadPath(int download_id, const Awesomium::WebString & path)
// void Awesomium::WebView::DidCancelDownload(int download_id)


