#include <plug_common.h>

#ifdef __cplusplus
extern "C" {
#endif

extern void register_defines(lua_State* L);
extern void register_enums(lua_State* L);
extern void register_global_functions(lua_State* L);

	
	
int PLUG_EXPORT luaopen_bullet(lua_State* L) {
	luna_open(L);

	luna_pushModule(L,"luna");
	Luna< void >::Register(L);
	luna_popModule(L);

	luna_pushModule(L,"bullet");
	Luna< btBroadphaseInterface >::Register(L);
	Luna< bt32BitAxisSweep3 >::Register(L);
	Luna< BT_BOX_BOX_TRANSFORM_CACHE >::Register(L);
	Luna< BT_QUANTIZED_BVH_NODE >::Register(L);
	Luna< btAABB >::Register(L);
	Luna< btCollisionAlgorithm >::Register(L);
	Luna< btActivatingCollisionAlgorithm >::Register(L);
	Luna< btAngleCompareFunc >::Register(L);
	Luna< btAxisSweep3 >::Register(L);
	Luna< btBroadphaseProxy >::Register(L);
	Luna< btBlock >::Register(L);
	Luna< btBox2dBox2dCollisionAlgorithm >::Register(L);
	Luna< btCollisionAlgorithmCreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btBox2dBox2dCollisionAlgorithm");
	Luna< btBox2dBox2dCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btCollisionShape >::Register(L);
	Luna< btConvexShape >::Register(L);
	Luna< btConvexInternalShape >::Register(L);
	Luna< btPolyhedralConvexShape >::Register(L);
	Luna< btBox2dShape >::Register(L);
	Luna< btBoxBoxCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btBoxBoxCollisionAlgorithm");
	Luna< btBoxBoxCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btDiscreteCollisionDetectorInterface >::Register(L);
	Luna< btBoxBoxDetector >::Register(L);
	Luna< btBoxShape >::Register(L);
	Luna< btBroadphaseAabbCallback >::Register(L);
	Luna< btBroadphasePair >::Register(L);
	Luna< btBroadphasePairSortPredicate >::Register(L);
	Luna< btBroadphaseRayCallback >::Register(L);
	Luna< btPolyhedralConvexAabbCachingShape >::Register(L);
	Luna< btBU_Simplex1to4 >::Register(L);
	Luna< btBvhSubtreeInfo >::Register(L);
	Luna< btBvhSubtreeInfoData >::Register(L);
	Luna< btBvhTree >::Register(L);
	Luna< btConcaveShape >::Register(L);
	Luna< btTriangleMeshShape >::Register(L);
	Luna< btBvhTriangleMeshShape >::Register(L);
	Luna< btCapsuleShape >::Register(L);
	Luna< btCapsuleShapeData >::Register(L);
	Luna< btCapsuleShapeX >::Register(L);
	Luna< btCapsuleShapeZ >::Register(L);
	Luna< btCharIndexTripletData >::Register(L);
	Luna< btChunk >::Register(L);
	Luna< btClock >::Register(L);
	Luna< btCollisionAlgorithmConstructionInfo >::Register(L);
	Luna< btCollisionConfiguration >::Register(L);
	Luna< btDispatcher >::Register(L);
	Luna< btCollisionDispatcher >::Register(L);
	Luna< btCollisionObject >::Register(L);
	Luna< btCollisionObjectDoubleData >::Register(L);
	Luna< btCollisionObjectFloatData >::Register(L);
	Luna< btCollisionObjectWrapper >::Register(L);
	Luna< btCollisionShapeData >::Register(L);
	Luna< btCollisionWorld >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btCollisionWorld");
	Luna< btCollisionWorld::RayResultCallback >::Register(L);
	Luna< btCollisionWorld::AllHitsRayResultCallback >::Register(L);
	Luna< btCollisionWorld::ConvexResultCallback >::Register(L);
	Luna< btCollisionWorld::ClosestConvexResultCallback >::Register(L);
	Luna< btCollisionWorld::ClosestRayResultCallback >::Register(L);
	Luna< btCollisionWorld::ContactResultCallback >::Register(L);
	Luna< btCollisionWorld::LocalConvexResult >::Register(L);
	Luna< btCollisionWorld::LocalRayResult >::Register(L);
	Luna< btCollisionWorld::LocalShapeInfo >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btCompoundCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btCompoundCollisionAlgorithm");
	Luna< btCompoundCollisionAlgorithm::CreateFunc >::Register(L);
	Luna< btCompoundCollisionAlgorithm::SwappedCreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btCompoundShape >::Register(L);
	Luna< btCompoundShapeChild >::Register(L);
	Luna< btCompoundShapeChildData >::Register(L);
	Luna< btCompoundShapeData >::Register(L);
	Luna< btConeShape >::Register(L);
	Luna< btConeShapeX >::Register(L);
	Luna< btConeShapeZ >::Register(L);
	Luna< btConstraintRow >::Register(L);
	Luna< btConvexCast >::Register(L);
	Luna< btContinuousConvexCollision >::Register(L);
	Luna< btConvex2dConvex2dAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvex2dConvex2dAlgorithm");
	Luna< btConvex2dConvex2dAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvex2dShape >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvexCast");
	Luna< btConvexCast::CastResult >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvexConcaveCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvexConcaveCollisionAlgorithm");
	Luna< btConvexConcaveCollisionAlgorithm::CreateFunc >::Register(L);
	Luna< btConvexConcaveCollisionAlgorithm::SwappedCreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvexConvexAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvexConvexAlgorithm");
	Luna< btConvexConvexAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvexHullComputer >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvexHullComputer");
	Luna< btConvexHullComputer::Edge >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvexHullShape >::Register(L);
	Luna< btConvexHullShapeData >::Register(L);
	Luna< btConvexInternalAabbCachingShape >::Register(L);
	Luna< btConvexInternalShapeData >::Register(L);
	Luna< btConvexPenetrationDepthSolver >::Register(L);
	Luna< btConvexPlaneCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btConvexPlaneCollisionAlgorithm");
	Luna< btConvexPlaneCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btConvexPointCloudShape >::Register(L);
	Luna< btConvexPolyhedron >::Register(L);
	Luna< btConvexSeparatingDistanceUtil >::Register(L);
	Luna< btTriangleCallback >::Register(L);
	Luna< btConvexTriangleCallback >::Register(L);
	Luna< btConvexTriangleMeshShape >::Register(L);
	Luna< btCylinderShape >::Register(L);
	Luna< btCylinderShapeData >::Register(L);
	Luna< btCylinderShapeX >::Register(L);
	Luna< btCylinderShapeZ >::Register(L);
	Luna< btDbvt >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btDbvt");
	Luna< btDbvt::IClone >::Register(L);
	Luna< btDbvt::ICollide >::Register(L);
	Luna< btDbvt::IWriter >::Register(L);
	Luna< btDbvt::sStkCLN >::Register(L);
	Luna< btDbvt::sStkNN >::Register(L);
	Luna< btDbvt::sStkNP >::Register(L);
	Luna< btDbvt::sStkNPS >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btDbvtAabbMm >::Register(L);
	Luna< btDbvtBroadphase >::Register(L);
	Luna< btDbvtNode >::Register(L);
	Luna< btDbvtProxy >::Register(L);
	Luna< btDefaultCollisionConfiguration >::Register(L);
	Luna< btDefaultCollisionConstructionInfo >::Register(L);
	Luna< btMotionState >::Register(L);
	Luna< btDefaultMotionState >::Register(L);
	Luna< btSerializer >::Register(L);
	Luna< btDefaultSerializer >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btDiscreteCollisionDetectorInterface");
	Luna< btDiscreteCollisionDetectorInterface::ClosestPointInput >::Register(L);
	Luna< btDiscreteCollisionDetectorInterface::Result >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btDispatcherInfo >::Register(L);
	Luna< btElement >::Register(L);
	Luna< btEmptyAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btEmptyAlgorithm");
	Luna< btEmptyAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btEmptyShape >::Register(L);
	Luna< btFace >::Register(L);
	Luna< btGEN_Link >::Register(L);
	Luna< btGEN_List >::Register(L);
	Luna< btGenericMemoryPool >::Register(L);
	Luna< btGenericPoolAllocator >::Register(L);
	Luna< btGeometryUtil >::Register(L);
	Luna< btGhostObject >::Register(L);
	Luna< btOverlappingPairCallback >::Register(L);
	Luna< btGhostPairCallback >::Register(L);
	Luna< btGImpactBvh >::Register(L);
	Luna< btGImpactCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btGImpactCollisionAlgorithm");
	Luna< btGImpactCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btGImpactShapeInterface >::Register(L);
	Luna< btGImpactCompoundShape >::Register(L);
	Luna< btPrimitiveManagerBase >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btGImpactCompoundShape");
	Luna< btGImpactCompoundShape::CompoundPrimitiveManager >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btGImpactMeshShape >::Register(L);
	Luna< btGImpactMeshShapeData >::Register(L);
	Luna< btGImpactMeshShapePart >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btGImpactMeshShapePart");
	Luna< btGImpactMeshShapePart::TrimeshPrimitiveManager >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btGImpactQuantizedBvh >::Register(L);
	Luna< btGjkConvexCast >::Register(L);
	Luna< btGjkEpaPenetrationDepthSolver >::Register(L);
	Luna< btGjkEpaSolver2 >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btGjkEpaSolver2");
	Luna< btGjkEpaSolver2::sResults >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btGjkPairDetector >::Register(L);
	Luna< btOverlappingPairCache >::Register(L);
	Luna< btHashedOverlappingPairCache >::Register(L);
	Luna< btHashInt >::Register(L);
	Luna< btHashPtr >::Register(L);
	Luna< btHashString >::Register(L);
	Luna< btHeightfieldTerrainShape >::Register(L);
	Luna< btIDebugDraw >::Register(L);
	Luna< btIndexedMesh >::Register(L);
	Luna< btInternalTriangleIndexCallback >::Register(L);
	Luna< btIntIndexData >::Register(L);
	Luna< btManifoldPoint >::Register(L);
	Luna< btManifoldResult >::Register(L);
	Luna< btMaterial >::Register(L);
	Luna< btMaterialProperties >::Register(L);
	Luna< btMatrix3x3 >::Register(L);
	Luna< btMatrix3x3DoubleData >::Register(L);
	Luna< btMatrix3x3FloatData >::Register(L);
	Luna< btMeshPartData >::Register(L);
	Luna< btMinkowskiPenetrationDepthSolver >::Register(L);
	Luna< btMinkowskiSumShape >::Register(L);
	Luna< btMultimaterialTriangleMeshShape >::Register(L);
	Luna< btMultiSapBroadphase >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btMultiSapBroadphase");
	Luna< btMultiSapBroadphase::btMultiSapProxy >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btMultiSphereShape >::Register(L);
	Luna< btMultiSphereShapeData >::Register(L);
	Luna< btNodeOverlapCallback >::Register(L);
	Luna< btNullPairCache >::Register(L);
	Luna< btQuantizedBvh >::Register(L);
	Luna< btOptimizedBvh >::Register(L);
	Luna< btOptimizedBvhNode >::Register(L);
	Luna< btOptimizedBvhNodeDoubleData >::Register(L);
	Luna< btOptimizedBvhNodeFloatData >::Register(L);
	Luna< btOverlapCallback >::Register(L);
	Luna< btOverlapFilterCallback >::Register(L);
	Luna< btPairCachingGhostObject >::Register(L);
	Luna< btTypedObject >::Register(L);
	Luna< btPersistentManifold >::Register(L);
	Luna< btPlane >::Register(L);
	Luna< btPointCollector >::Register(L);
	Luna< btPointerUid >::Register(L);
	Luna< btPolarDecomposition >::Register(L);
	Luna< btPolyhedralContactClipping >::Register(L);
	Luna< btPoolAllocator >::Register(L);
	Luna< btPositionAndRadius >::Register(L);
	Luna< btPrimitiveTriangle >::Register(L);
	Luna< btQuadWord >::Register(L);
	Luna< btQuantizedBvhDoubleData >::Register(L);
	Luna< btQuantizedBvhFloatData >::Register(L);
	Luna< btQuantizedBvhNode >::Register(L);
	Luna< btQuantizedBvhNodeData >::Register(L);
	Luna< btQuantizedBvhTree >::Register(L);
	Luna< btQuaternion >::Register(L);
	Luna< btScaledBvhTriangleMeshShape >::Register(L);
	Luna< btScaledTriangleMeshShapeData >::Register(L);
	Luna< btShapeHull >::Register(L);
	Luna< btShortIntIndexData >::Register(L);
	Luna< btShortIntIndexTripletData >::Register(L);
	Luna< btSimpleBroadphase >::Register(L);
	Luna< btSimpleBroadphaseProxy >::Register(L);
	Luna< btSimulationIslandManager >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btSimulationIslandManager");
	Luna< btSimulationIslandManager::IslandCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btSortedOverlappingPairCache >::Register(L);
	Luna< btSphereBoxCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btSphereBoxCollisionAlgorithm");
	Luna< btSphereBoxCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btSphereShape >::Register(L);
	Luna< btSphereSphereCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btSphereSphereCollisionAlgorithm");
	Luna< btSphereSphereCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btSphereTriangleCollisionAlgorithm >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"btSphereTriangleCollisionAlgorithm");
	Luna< btSphereTriangleCollisionAlgorithm::CreateFunc >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< btStackAlloc >::Register(L);
	Luna< btStaticPlaneShape >::Register(L);
	Luna< btStaticPlaneShapeData >::Register(L);
	Luna< btStorageResult >::Register(L);
	Luna< btStridingMeshInterface >::Register(L);
	Luna< btStridingMeshInterfaceData >::Register(L);
	Luna< btSubSimplexClosestResult >::Register(L);
	Luna< btSubsimplexConvexCast >::Register(L);
	Luna< btTetrahedronShapeEx >::Register(L);
	Luna< btTransform >::Register(L);
	Luna< btTransformDoubleData >::Register(L);
	Luna< btTransformFloatData >::Register(L);
	Luna< btTransformUtil >::Register(L);
	Luna< btTriangle >::Register(L);
	Luna< btTriangleBuffer >::Register(L);
	Luna< btTriangleConvexcastCallback >::Register(L);
	Luna< btTriangleIndexVertexArray >::Register(L);
	Luna< btTriangleIndexVertexMaterialArray >::Register(L);
	Luna< btTriangleInfo >::Register(L);
	Luna< btTriangleInfoData >::Register(L);
	Luna< btTriangleInfoMapData >::Register(L);
	Luna< btTriangleMesh >::Register(L);
	Luna< btTriangleMeshShapeData >::Register(L);
	Luna< btTriangleRaycastCallback >::Register(L);
	Luna< btTriangleShape >::Register(L);
	Luna< btTriangleShapeEx >::Register(L);
	Luna< btUniformScalingShape >::Register(L);
	Luna< btUnionFind >::Register(L);
	Luna< btUsageBitfield >::Register(L);
	Luna< btVector3 >::Register(L);
	Luna< btVector3DoubleData >::Register(L);
	Luna< btVector3FloatData >::Register(L);
	Luna< btVector4 >::Register(L);
	Luna< btVoronoiSimplexSolver >::Register(L);
	Luna< ConvexH >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"ConvexH");
	Luna< ConvexH::HalfEdge >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"bullet");
	Luna< CProfileIterator >::Register(L);
	Luna< CProfileManager >::Register(L);
	Luna< CProfileNode >::Register(L);
	Luna< CProfileSample >::Register(L);
	Luna< GIM_BVH_DATA >::Register(L);
	Luna< GIM_BVH_TREE_NODE >::Register(L);
	Luna< GIM_CONTACT >::Register(L);
	Luna< GIM_PAIR >::Register(L);
	Luna< GIM_TRIANGLE_CONTACT >::Register(L);
	Luna< GrahamVector3 >::Register(L);
	Luna< HullDesc >::Register(L);
	Luna< HullLibrary >::Register(L);
	Luna< HullResult >::Register(L);
	Luna< int4 >::Register(L);
	Luna< PHullResult >::Register(L);
	Luna< SphereTriangleDetector >::Register(L);
	Luna< btAlignedObjectArray< btPersistentManifold * > >::Register(L);
	Luna< btAlignedObjectArray< btCollisionObject * > >::Register(L);
	Luna< btAlignedObjectArray< unsigned int > >::Register(L);
	Luna< btAlignedObjectArray< btDbvtProxy * > >::Register(L);
	Luna< btAlignedObjectArray< btBroadphaseInterface * > >::Register(L);
	Luna< btAlignedObjectArray< btBroadphasePair > >::Register(L);
	Luna< btAlignedObjectArray< btVector3 > >::Register(L);
	Luna< btAlignedObjectArray< btOptimizedBvhNode > >::Register(L);
	Luna< btAlignedObjectArray< btQuantizedBvhNode > >::Register(L);
	Luna< btAlignedObjectArray< btBvhSubtreeInfo > >::Register(L);
	Luna< btAlignedObjectArray< btIndexedMesh > >::Register(L);
	Luna< btAlignedObjectArray< btMaterialProperties > >::Register(L);
	Luna< btHashMap< btHashInt, btTriangleInfo > >::Register(L);
	Luna< btAlignedObjectArray< int > >::Register(L);
	Luna< btAlignedObjectArray< const btCollisionObject * > >::Register(L);
	Luna< btAlignedObjectArray< float > >::Register(L);
	Luna< btAlignedObjectArray< btConvexHullComputer::Edge > >::Register(L);
	Luna< btAlignedObjectArray< btFace > >::Register(L);
	Luna< btAlignedObjectArray< const btDbvtNode * > >::Register(L);
	Luna< btAlignedObjectArray< btDbvt::sStkNPS > >::Register(L);
	Luna< btAlignedObjectArray< btDbvt::sStkNN > >::Register(L);
	Luna< btAlignedObjectArray< ConvexH::HalfEdge > >::Register(L);
	Luna< btAlignedObjectArray< btPlane > >::Register(L);
	Luna< btAlignedObjectArray< GrahamVector3 > >::Register(L);
	luna_popModule(L);

	luna_pushModule(L,"bullet");

	register_defines(L);

	register_enums(L);

	luna_popModule(L);

	register_global_functions(L);

	luna_copyParents(L,"bullet");
	luna_copyParents(L,"btBox2dBox2dCollisionAlgorithm");
	luna_copyParents(L,"btBoxBoxCollisionAlgorithm");
	luna_copyParents(L,"btCollisionWorld");
	luna_copyParents(L,"btCompoundCollisionAlgorithm");
	luna_copyParents(L,"btConvex2dConvex2dAlgorithm");
	luna_copyParents(L,"btConvexCast");
	luna_copyParents(L,"btConvexConcaveCollisionAlgorithm");
	luna_copyParents(L,"btConvexConvexAlgorithm");
	luna_copyParents(L,"btConvexHullComputer");
	luna_copyParents(L,"btConvexPlaneCollisionAlgorithm");
	luna_copyParents(L,"btDbvt");
	luna_copyParents(L,"btDiscreteCollisionDetectorInterface");
	luna_copyParents(L,"btEmptyAlgorithm");
	luna_copyParents(L,"btGImpactCollisionAlgorithm");
	luna_copyParents(L,"btGImpactCompoundShape");
	luna_copyParents(L,"btGImpactMeshShapePart");
	luna_copyParents(L,"btGjkEpaSolver2");
	luna_copyParents(L,"btMultiSapBroadphase");
	luna_copyParents(L,"btSimulationIslandManager");
	luna_copyParents(L,"btSphereBoxCollisionAlgorithm");
	luna_copyParents(L,"btSphereSphereCollisionAlgorithm");
	luna_copyParents(L,"btSphereTriangleCollisionAlgorithm");
	luna_copyParents(L,"ConvexH");

	luna_pushModule(L,"bullet");
	return 1;
}

#ifdef __cplusplus
}
#endif

