#include <plug_common.h>

#ifdef __cplusplus
extern "C" {
#endif

extern void register_defines(lua_State* L);
extern void register_enums(lua_State* L);
extern void register_global_functions(lua_State* L);

int PLUG_EXPORT luaopen_osg(lua_State* L) {
	luna_open(L);

	lua_newtable(L); // container class

	register_defines(L);

	register_enums(L);

	Luna< void >::Register(L);
	Luna< GLUtesselator >::Register(L);
	Luna< osg::TemplateIndexArray< signed char, osg::Array::ByteArrayType, 1, GL_BYTE > >::Register(L);
	Luna< osg::TemplateIndexArray< short, osg::Array::ShortArrayType, 1, GL_SHORT > >::Register(L);
	Luna< osg::TemplateIndexArray< int, osg::Array::IntArrayType, 1, 0x1404 > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned char, osg::Array::UByteArrayType, 1, GL_UNSIGNED_BYTE > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned short, osg::Array::UShortArrayType, 1, GL_UNSIGNED_SHORT > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned int, osg::Array::UIntArrayType, 1, 0x1405 > >::Register(L);
	Luna< osg::TemplateArray< float, osg::Array::FloatArrayType, 1, GL_FLOAT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2f, osg::Array::Vec2ArrayType, 2, GL_FLOAT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3f, osg::Array::Vec3ArrayType, 3, GL_FLOAT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4f, osg::Array::Vec4ArrayType, 4, GL_FLOAT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4ub, osg::Array::Vec4ubArrayType, 4, GL_UNSIGNED_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2s, osg::Array::Vec2sArrayType, 2, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3s, osg::Array::Vec3sArrayType, 3, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4s, osg::Array::Vec4sArrayType, 4, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2b, osg::Array::Vec2bArrayType, 2, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3b, osg::Array::Vec3bArrayType, 3, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4b, osg::Array::Vec4bArrayType, 4, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< double, osg::Array::DoubleArrayType, 1, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2d, osg::Array::Vec2dArrayType, 2, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3d, osg::Array::Vec3dArrayType, 3, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4d, osg::Array::Vec4dArrayType, 4, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Matrixf, osg::Array::MatrixArrayType, 16, GL_FLOAT > >::Register(L);
	Luna< osg::BoundingBoxImpl< osg::Vec3f > >::Register(L);
	Luna< osg::BoundingBoxImpl< osg::Vec3d > >::Register(L);
	Luna< osg::BoundingSphereImpl< osg::Vec3f > >::Register(L);
	Luna< osg::BoundingSphereImpl< osg::Vec3d > >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::GLBufferObject > > >::Register(L);
	Luna< std::pair< double, double > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Node > > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Image > > >::Register(L);
	Luna< std::vector< osg::Node * > >::Register(L);
	Luna< std::vector< osg::NodePath > >::Register(L);
	Luna< std::vector< osg::Matrixd > >::Register(L);
	Luna< osg::MixinVector< int > >::Register(L);
	Luna< osg::MixinVector< unsigned char > >::Register(L);
	Luna< osg::MixinVector< unsigned short > >::Register(L);
	Luna< osg::MixinVector< unsigned int > >::Register(L);
	Luna< std::vector< osg::ShaderComponent * > >::Register(L);
	Luna< std::vector< osg::ShadowVolumeOccluder > >::Register(L);
	Luna< osg::TemplateValueObject< std::string > >::Register(L);
	Luna< osg::TemplateValueObject< bool > >::Register(L);
	Luna< osg::TemplateValueObject< char > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned char > >::Register(L);
	Luna< osg::TemplateValueObject< short > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned short > >::Register(L);
	Luna< osg::TemplateValueObject< int > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned int > >::Register(L);
	Luna< osg::TemplateValueObject< float > >::Register(L);
	Luna< osg::TemplateValueObject< double > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec2f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec3f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec4f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec2d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec3d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec4d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Quat > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Plane > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Matrixf > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Matrixd > >::Register(L);
	Luna< std::vector< osg::Vec3d > >::Register(L);
	Luna< std::vector< osg::StateSet const * > >::Register(L);
	Luna< std::vector< std::pair< osg::StateAttribute const *, unsigned int > > >::Register(L);
	Luna< osg::Referenced >::Register(L);
	Luna< osg::Object >::Register(L);
	Luna< osg::StateAttribute >::Register(L);
	Luna< osg::AlphaFunc >::Register(L);
	Luna< osg::AnimationPath >::Register(L);
	Luna< std::map< double, osg::AnimationPath::ControlPoint > >::Register(L);
	Luna< osg::AnimationPath::ControlPoint >::Register(L);
	Luna< osg::NodeCallback >::Register(L);
	Luna< osg::AnimationPathCallback >::Register(L);
	Luna< osg::ApplicationUsage >::Register(L);
	Luna< std::map< std::string, std::string > >::Register(L);
	Luna< osg::ApplicationUsageProxy >::Register(L);
	Luna< osg::ArgumentParser >::Register(L);
	Luna< std::map< std::string, osg::ArgumentParser::ErrorSeverity > >::Register(L);
	Luna< osg::ArgumentParser::Parameter >::Register(L);
	Luna< osg::BufferData >::Register(L);
	Luna< osg::Array >::Register(L);
	Luna< osg::IndexArray >::Register(L);
	Luna< osg::ArrayVisitor >::Register(L);
	Luna< osg::ConstArrayVisitor >::Register(L);
	Luna< osg::ValueVisitor >::Register(L);
	Luna< osg::ConstValueVisitor >::Register(L);
	Luna< osg::AttributeDispatch >::Register(L);
	Luna< osg::ArrayDispatchers >::Register(L);
	Luna< osg::AudioSink >::Register(L);
	Luna< osg::AudioStream >::Register(L);
	Luna< osg::Node >::Register(L);
	Luna< osg::Group >::Register(L);
	Luna< osg::Transform >::Register(L);
	Luna< osg::AutoTransform >::Register(L);
	Luna< osg::Geode >::Register(L);
	Luna< osg::Billboard >::Register(L);
	Luna< std::vector< osg::Vec3f > >::Register(L);
	Luna< osg::BlendColor >::Register(L);
	Luna< osg::BlendColor::Extensions >::Register(L);
	Luna< osg::BlendEquation >::Register(L);
	Luna< osg::BlendEquation::Extensions >::Register(L);
	Luna< osg::BlendFunc >::Register(L);
	Luna< osg::BlendFunc::Extensions >::Register(L);
	Luna< osg::BufferIndexBinding >::Register(L);
	Luna< osg::UniformBufferBinding >::Register(L);
	Luna< osg::TransformFeedbackBufferBinding >::Register(L);
	Luna< osg::BufferObjectProfile >::Register(L);
	Luna< osg::GLBufferObject >::Register(L);
	Luna< osg::GLBufferObject::BufferEntry >::Register(L);
	Luna< osg::GLBufferObject::Extensions >::Register(L);
	Luna< osg::GLBufferObjectSet >::Register(L);
	Luna< osg::GLBufferObjectManager >::Register(L);
	Luna< osg::BufferObject >::Register(L);
	Luna< osg::BufferData::ModifiedCallback >::Register(L);
	Luna< osg::VertexBufferObject >::Register(L);
	Luna< osg::ElementBufferObject >::Register(L);
	Luna< osg::PixelBufferObject >::Register(L);
	Luna< osg::PixelDataBufferObject >::Register(L);
	Luna< osg::UniformBufferObject >::Register(L);
	Luna< osg::CullSettings >::Register(L);
	Luna< osg::Camera >::Register(L);
	Luna< std::map< osg::Camera::BufferComponent, osg::Camera::Attachment > >::Register(L);
	Luna< osg::Camera::Attachment >::Register(L);
	Luna< osg::Camera::DrawCallback >::Register(L);
	Luna< osg::CameraView >::Register(L);
	Luna< osg::ClampColor >::Register(L);
	Luna< osg::ClampColor::Extensions >::Register(L);
	Luna< osg::ClearNode >::Register(L);
	Luna< osg::ClipNode >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::ClipPlane > > >::Register(L);
	Luna< osg::ClipPlane >::Register(L);
	Luna< osg::Drawable::CullCallback >::Register(L);
	Luna< osg::ClusterCullingCallback >::Register(L);
	Luna< osg::CullStack >::Register(L);
	Luna< osg::NodeVisitor >::Register(L);
	Luna< osg::CollectOccludersVisitor >::Register(L);
	Luna< std::set< osg::ShadowVolumeOccluder > >::Register(L);
	Luna< osg::ColorMask >::Register(L);
	Luna< osg::ColorMatrix >::Register(L);
	Luna< osg::ComputeBoundsVisitor >::Register(L);
	Luna< osg::ConvexPlanarOccluder >::Register(L);
	Luna< std::vector< osg::ConvexPlanarPolygon > >::Register(L);
	Luna< osg::ConvexPlanarPolygon >::Register(L);
	Luna< osg::EllipsoidModel >::Register(L);
	Luna< osg::CoordinateSystemNode >::Register(L);
	Luna< osg::CopyOp >::Register(L);
	Luna< osg::CullFace >::Register(L);
	Luna< osg::CullingSet >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::StateSet >, osg::Polytope > >::Register(L);
	Luna< std::vector< osg::CullingSet::StateFrustumPair > >::Register(L);
	Luna< osg::CullSettings::ClampProjectionMatrixCallback >::Register(L);
	Luna< std::vector< osg::CullingSet > >::Register(L);
	Luna< osg::DeleteHandler >::Register(L);
	Luna< std::pair< unsigned int, const osg::Referenced * > >::Register(L);
	Luna< std::list< osg::DeleteHandler::FrameNumberObjectPair > >::Register(L);
	Luna< osg::Depth >::Register(L);
	Luna< osg::DisplaySettings >::Register(L);
	Luna< osg::Drawable >::Register(L);
	Luna< osg::Drawable::AttributeFunctor >::Register(L);
	Luna< osg::Drawable::ComputeBoundingBoxCallback >::Register(L);
	Luna< osg::Drawable::ConstAttributeFunctor >::Register(L);
	Luna< osg::Drawable::DrawCallback >::Register(L);
	Luna< osg::Drawable::EventCallback >::Register(L);
	Luna< osg::Drawable::Extensions >::Register(L);
	Luna< osg::Drawable::UpdateCallback >::Register(L);
	Luna< osg::DrawPixels >::Register(L);
	Luna< osg::Fog >::Register(L);
	Luna< osg::FragmentProgram >::Register(L);
	Luna< std::map< unsigned int, osg::Vec4f > >::Register(L);
	Luna< std::map< unsigned int, osg::Matrixd > >::Register(L);
	Luna< osg::FragmentProgram::Extensions >::Register(L);
	Luna< osg::FBOExtensions >::Register(L);
	Luna< osg::RenderBuffer >::Register(L);
	Luna< osg::FrameBufferAttachment >::Register(L);
	Luna< osg::FrameBufferObject >::Register(L);
	Luna< std::map< osg::Camera::BufferComponent, osg::FrameBufferAttachment > >::Register(L);
	Luna< std::vector< unsigned int > >::Register(L);
	Luna< osg::FrameStamp >::Register(L);
	Luna< osg::FrontFace >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Drawable > > >::Register(L);
	Luna< osg::Geometry >::Register(L);
	Luna< std::vector< osg::Geometry::ArrayData > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::PrimitiveSet > > >::Register(L);
	Luna< std::vector< osg::Array * > >::Register(L);
	Luna< std::vector< osg::DrawElements * > >::Register(L);
	Luna< osg::Geometry::ArrayData >::Register(L);
	Luna< osg::Geometry::Vec3ArrayData >::Register(L);
	Luna< osg::GL2Extensions >::Register(L);
	Luna< osg::GLBeginEndAdapter >::Register(L);
	Luna< osg::PixelStorageModes >::Register(L);
	Luna< osg::GraphicsContext >::Register(L);
	Luna< std::vector< osg::GraphicsContext::ScreenSettings > >::Register(L);
	Luna< std::vector< osg::GraphicsContext * > >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::Operation > > >::Register(L);
	Luna< std::list< osg::Camera * > >::Register(L);
	Luna< osg::GraphicsContext::ResizedCallback >::Register(L);
	Luna< osg::GraphicsContext::ScreenIdentifier >::Register(L);
	Luna< osg::GraphicsContext::ScreenSettings >::Register(L);
	Luna< osg::GraphicsContext::SwapCallback >::Register(L);
	Luna< osg::GraphicsContext::Traits >::Register(L);
	Luna< osg::GraphicsContext::WindowingSystemInterface >::Register(L);
	Luna< osg::ClampedLinearCostFunction1D >::Register(L);
	Luna< osg::GeometryCostEstimator >::Register(L);
	Luna< osg::TextureCostEstimator >::Register(L);
	Luna< osg::ProgramCostEstimator >::Register(L);
	Luna< osg::GraphicsCostEstimator >::Register(L);
	Luna< osg::OperationThread >::Register(L);
	Luna< osg::GraphicsThread >::Register(L);
	Luna< osg::Operation >::Register(L);
	Luna< osg::GraphicsOperation >::Register(L);
	Luna< osg::SwapBuffersOperation >::Register(L);
	Luna< osg::BarrierOperation >::Register(L);
	Luna< osg::RefBlock >::Register(L);
	Luna< osg::ReleaseContext_Block_MakeCurrentOperation >::Register(L);
	Luna< osg::BlockAndFlushOperation >::Register(L);
	Luna< osg::FlushDeletedGLObjectsOperation >::Register(L);
	Luna< osg::RunOperations >::Register(L);
	Luna< osg::State::DynamicObjectRenderingCompletedCallback >::Register(L);
	Luna< osg::EndOfDynamicDrawBlock >::Register(L);
	Luna< osg::Hint >::Register(L);
	Luna< osg::Image >::Register(L);
	Luna< osg::StateAttributeCallback >::Register(L);
	Luna< osg::Image::UpdateCallback >::Register(L);
	Luna< osg::ImageStream >::Register(L);
	Luna< osg::ImageSequence >::Register(L);
	Luna< std::vector< std::string > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::AudioStream > > >::Register(L);
	Luna< osg::Shape >::Register(L);
	Luna< osg::KdTree >::Register(L);
	Luna< std::vector< osg::KdTree::LineSegmentIntersection > >::Register(L);
	Luna< std::vector< osg::KdTree::KdNode > >::Register(L);
	Luna< std::vector< osg::KdTree::Triangle > >::Register(L);
	Luna< osg::KdTree::BuildOptions >::Register(L);
	Luna< osg::KdTree::KdNode >::Register(L);
	Luna< osg::KdTree::LineSegmentIntersection >::Register(L);
	Luna< std::vector< double > >::Register(L);
	Luna< osg::KdTree::Triangle >::Register(L);
	Luna< osg::KdTreeBuilder >::Register(L);
	Luna< osg::Light >::Register(L);
	Luna< osg::LightModel >::Register(L);
	Luna< osg::LightSource >::Register(L);
	Luna< osg::LineSegment >::Register(L);
	Luna< osg::LineStipple >::Register(L);
	Luna< osg::LineWidth >::Register(L);
	Luna< osg::LOD >::Register(L);
	Luna< std::pair< float, float > >::Register(L);
	Luna< std::vector< osg::LOD::MinMaxPair > >::Register(L);
	Luna< osg::LogicOp >::Register(L);
	Luna< osg::Material >::Register(L);
	Luna< osg::Matrixd >::Register(L);
	Luna< osg::RefMatrixd >::Register(L);
	Luna< osg::Matrixf >::Register(L);
	Luna< osg::RefMatrixf >::Register(L);
	Luna< osg::MatrixTransform >::Register(L);
	Luna< osg::Multisample >::Register(L);
	Luna< osg::Multisample::Extensions >::Register(L);
	Luna< std::vector< osg::Group * > >::Register(L);
	Luna< osg::Node::ComputeBoundingSphereCallback >::Register(L);
	Luna< osg::NodeTrackerCallback >::Register(L);
	Luna< osg::NodeVisitor::DatabaseRequestHandler >::Register(L);
	Luna< osg::NodeVisitor::ImageRequestHandler >::Register(L);
	Luna< osg::NodeAcceptOp >::Register(L);
	Luna< osg::NotifyHandler >::Register(L);
	Luna< osg::StandardNotifyHandler >::Register(L);
	Luna< osg::Observer >::Register(L);
	Luna< osg::ObserverSet >::Register(L);
	Luna< std::set< osg::Observer * > >::Register(L);
	Luna< osg::ObserverNodePath >::Register(L);
	Luna< osg::OccluderNode >::Register(L);
	Luna< osg::TestResult >::Register(L);
	Luna< osg::QueryGeometry >::Register(L);
	Luna< osg::OcclusionQueryNode >::Register(L);
	Luna< osg::RefBlockCount >::Register(L);
	Luna< osg::OperationQueue >::Register(L);
	Luna< std::set< osg::OperationThread * > >::Register(L);
	Luna< osg::PagedLOD >::Register(L);
	Luna< std::vector< osg::PagedLOD::PerRangeData > >::Register(L);
	Luna< osg::PagedLOD::PerRangeData >::Register(L);
	Luna< osg::Plane >::Register(L);
	Luna< osg::Point >::Register(L);
	Luna< osg::Point::Extensions >::Register(L);
	Luna< osg::PointSprite >::Register(L);
	Luna< osg::PolygonMode >::Register(L);
	Luna< osg::PolygonOffset >::Register(L);
	Luna< osg::PolygonStipple >::Register(L);
	Luna< osg::Polytope >::Register(L);
	Luna< std::vector< osg::Plane > >::Register(L);
	Luna< osg::fast_back_stack< unsigned int > >::Register(L);
	Luna< osg::PositionAttitudeTransform >::Register(L);
	Luna< osg::PrimitiveFunctor >::Register(L);
	Luna< osg::PrimitiveIndexFunctor >::Register(L);
	Luna< osg::PrimitiveSet >::Register(L);
	Luna< osg::DrawArrays >::Register(L);
	Luna< osg::DrawArrayLengths >::Register(L);
	Luna< osg::DrawElements >::Register(L);
	Luna< osg::DrawElementsUByte >::Register(L);
	Luna< osg::DrawElementsUShort >::Register(L);
	Luna< osg::DrawElementsUInt >::Register(L);
	Luna< osg::Program >::Register(L);
	Luna< std::map< std::string, unsigned int > >::Register(L);
	Luna< std::map< unsigned int, osg::Program::ActiveVarInfo > >::Register(L);
	Luna< std::map< std::string, osg::Program::ActiveVarInfo > >::Register(L);
	Luna< std::map< std::string, osg::Program::UniformBlockInfo > >::Register(L);
	Luna< osg::Program::ActiveVarInfo >::Register(L);
	Luna< osg::Program::PerContextProgram >::Register(L);
	Luna< osg::Program::ProgramBinary >::Register(L);
	Luna< osg::Program::UniformBlockInfo >::Register(L);
	Luna< osg::Projection >::Register(L);
	Luna< osg::ProxyNode >::Register(L);
	Luna< osg::Quat >::Register(L);
	Luna< osg::RenderInfo >::Register(L);
	Luna< osg::Scissor >::Register(L);
	Luna< osg::Sequence >::Register(L);
	Luna< osg::ShadeModel >::Register(L);
	Luna< osg::ShaderBinary >::Register(L);
	Luna< osg::Shader >::Register(L);
	Luna< std::multimap< float, std::string > >::Register(L);
	Luna< osg::Shader::PerContextShader >::Register(L);
	Luna< osg::ShaderComponent >::Register(L);
	Luna< osg::ShaderAttribute >::Register(L);
	Luna< osg::ShaderComposer >::Register(L);
	Luna< std::vector< const osg::Shader * > >::Register(L);
	Luna< osg::ShadowVolumeOccluder >::Register(L);
	Luna< std::vector< osg::Polytope > >::Register(L);
	Luna< osg::ShapeVisitor >::Register(L);
	Luna< osg::ConstShapeVisitor >::Register(L);
	Luna< osg::Sphere >::Register(L);
	Luna< osg::Box >::Register(L);
	Luna< osg::Cone >::Register(L);
	Luna< osg::Cylinder >::Register(L);
	Luna< osg::Capsule >::Register(L);
	Luna< osg::InfinitePlane >::Register(L);
	Luna< osg::TriangleMesh >::Register(L);
	Luna< osg::ConvexHull >::Register(L);
	Luna< osg::HeightField >::Register(L);
	Luna< std::vector< float > >::Register(L);
	Luna< osg::CompositeShape >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Shape > > >::Register(L);
	Luna< osg::TessellationHints >::Register(L);
	Luna< osg::ShapeDrawable >::Register(L);
	Luna< osg::VertexAttribAlias >::Register(L);
	Luna< osg::State >::Register(L);
	Luna< std::pair< osg::StateAttribute::Type, unsigned int > >::Register(L);
	Luna< std::vector< osg::StateSet * > >::Register(L);
	Luna< osg::StateAttribute::ModeUsage >::Register(L);
	Luna< osg::StateSet >::Register(L);
	Luna< std::vector< osg::Object * > >::Register(L);
	Luna< std::map< unsigned int, unsigned int > >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::StateAttribute >, unsigned int > >::Register(L);
	Luna< std::map< osg::StateAttribute::TypeMemberPair, osg::StateSet::RefAttributePair > >::Register(L);
	Luna< std::vector< osg::StateSet::ModeList > >::Register(L);
	Luna< std::vector< osg::StateSet::AttributeList > >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::Uniform >, unsigned int > >::Register(L);
	Luna< std::map< std::string, osg::StateSet::RefUniformPair > >::Register(L);
	Luna< osg::StateSet::Callback >::Register(L);
	Luna< osg::Stats >::Register(L);
	Luna< std::map< std::string, double > >::Register(L);
	Luna< std::vector< osg::Stats::AttributeMap > >::Register(L);
	Luna< std::map< std::string, bool > >::Register(L);
	Luna< osg::Stencil >::Register(L);
	Luna< osg::Stencil::Extensions >::Register(L);
	Luna< osg::StencilTwoSided >::Register(L);
	Luna< osg::StencilTwoSided::Extensions >::Register(L);
	Luna< osg::Switch >::Register(L);
	Luna< std::vector< bool > >::Register(L);
	Luna< osg::TexEnv >::Register(L);
	Luna< osg::TexEnvCombine >::Register(L);
	Luna< osg::TexEnvFilter >::Register(L);
	Luna< osg::TexGen >::Register(L);
	Luna< osg::TexGenNode >::Register(L);
	Luna< osg::TexMat >::Register(L);
	Luna< osg::Texture >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::Texture::TextureObject > > >::Register(L);
	Luna< osg::Texture::Extensions >::Register(L);
	Luna< osg::Texture::TextureObject >::Register(L);
	Luna< osg::Texture::TextureObjectManager >::Register(L);
	Luna< osg::Texture::TextureObjectSet >::Register(L);
	Luna< osg::Texture::TextureProfile >::Register(L);
	Luna< osg::Texture1D >::Register(L);
	Luna< osg::Texture1D::SubloadCallback >::Register(L);
	Luna< osg::Texture2D >::Register(L);
	Luna< osg::Texture2D::SubloadCallback >::Register(L);
	Luna< osg::Texture2DArray >::Register(L);
	Luna< osg::Texture2DArray::Extensions >::Register(L);
	Luna< osg::Texture2DArray::SubloadCallback >::Register(L);
	Luna< osg::Texture2DMultisample >::Register(L);
	Luna< osg::Texture3D >::Register(L);
	Luna< osg::Texture3D::Extensions >::Register(L);
	Luna< osg::Texture3D::SubloadCallback >::Register(L);
	Luna< osg::TextureCubeMap >::Register(L);
	Luna< osg::TextureCubeMap::Extensions >::Register(L);
	Luna< osg::TextureCubeMap::SubloadCallback >::Register(L);
	Luna< osg::TextureRectangle >::Register(L);
	Luna< osg::TextureRectangle::SubloadCallback >::Register(L);
	Luna< osg::Timer >::Register(L);
	Luna< osg::ElapsedTime >::Register(L);
	Luna< osg::TransferFunction >::Register(L);
	Luna< osg::TransferFunction1D >::Register(L);
	Luna< std::map< float, osg::Vec4f > >::Register(L);
	Luna< osg::Matrix2 >::Register(L);
	Luna< osg::Matrix3 >::Register(L);
	Luna< osg::Uniform >::Register(L);
	Luna< osg::Uniform::Callback >::Register(L);
	Luna< osg::UserDataContainer >::Register(L);
	Luna< osg::DefaultUserDataContainer >::Register(L);
	Luna< osg::ValueObject >::Register(L);
	Luna< osg::ValueObject::GetValueVisitor >::Register(L);
	Luna< osg::ValueObject::SetValueVisitor >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< std::string > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< bool > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< char > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned char > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< short > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned short > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< int > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned int > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< float > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< double > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec2f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec3f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec4f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec2d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec3d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec4d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Quat > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Plane > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Matrixf > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Matrixd > >::Register(L);
	Luna< osg::Vec2b >::Register(L);
	Luna< osg::Vec2d >::Register(L);
	Luna< osg::Vec2f >::Register(L);
	Luna< osg::Vec2s >::Register(L);
	Luna< osg::Vec3b >::Register(L);
	Luna< osg::Vec3d >::Register(L);
	Luna< osg::Vec3f >::Register(L);
	Luna< osg::Vec3s >::Register(L);
	Luna< osg::Vec4b >::Register(L);
	Luna< osg::Vec4d >::Register(L);
	Luna< osg::Vec4f >::Register(L);
	Luna< osg::Vec4s >::Register(L);
	Luna< osg::Vec4ub >::Register(L);
	Luna< osg::VertexProgram >::Register(L);
	Luna< osg::VertexProgram::Extensions >::Register(L);
	Luna< osg::View >::Register(L);
	Luna< osg::View::Slave >::Register(L);
	Luna< osg::View::Slave::UpdateSlaveCallback >::Register(L);
	Luna< osg::Viewport >::Register(L);

	register_global_functions(L);

	lua_pushstring(L,"osg");
	lua_setfield(L,-2,"__NAME__");

	lua_setglobal(L,"osg");
	lua_getglobal(L,"osg");

	luna_copyParents(L,"osg");

	return 1;
}

#ifdef __cplusplus
}
#endif

