SET(DEPS_DIR "W:/Cloud/Dev/Deps" CACHE STRING "Folder containing all the needed dependencies")
SET(TOOLS_DIR "W:/Cloud/Dev/Tools/win32" CACHE STRING "Folder containing all the needed dev tools")
SET(CMAKE_INSTALL_PREFIX "W:/Cloud/Projects/singularity/software" CACHE STRING "Installation folder")
SET(SGT_DIR "W:/Cloud/Projects/singularity" CACHE STRING "Root path of Singularity project")

SET(DOT_DIR "${TOOLS_DIR}/GraphViz-2.28.0/bin" CACHE STRING "Path where dot.exe can be found")
SET(HHC_DIR "${TOOLS_DIR}/HtmlHelpWorkshop-1.3" CACHE STRING "Path where hhc.exe can be found")
SET(DOXYGEN "${TOOLS_DIR}/doxygen-1.8.0/doxygen.exe" CACHE STRING "Doxygen executable")

SET(DEP_LUABIND ${DEPS_DIR}/${FLAVOR}/luabind-0.9.1 CACHE STRING "luabind path")
SET(DEP_LUA ${DEPS_DIR}/${FLAVOR}/LuaJIT-2.0.0-beta9 CACHE STRING "lua path")
SET(DEP_BOOST ${DEPS_DIR}/${FLAVOR}/boost-1.51.0 CACHE STRING "boost path")
SET(DEP_WX ${DEPS_DIR}/${FLAVOR}/wxWidgets-2.9.3 CACHE STRING "wx path")
SET(DEP_OSG ${DEPS_DIR}/${FLAVOR}/OpenSceneGraph-3.0.1 CACHE STRING "osg path")
SET(DEP_MYSQL ${DEPS_DIR}/${FLAVOR}/mysql-5.5.25 CACHE STRING "mysql path")
SET(DEP_FIREBIRD ${DEPS_DIR}/${FLAVOR}/Firebird-2.5.1.26351-0 CACHE STRING "firebird path")
SET(DEP_ZLIB ${DEPS_DIR}/${FLAVOR}/zlib-1.2.7 CACHE STRING "zlib path")
SET(DEP_OPENSSL ${DEPS_DIR}/${FLAVOR}/openssl-0.9.8x CACHE STRING "openssl path")
SET(DEP_SPARK ${DEPS_DIR}/${FLAVOR}/SPARK-1.5.5 CACHE STRING "spark path")
#SET(DEP_AWESOMIUM ${DEPS_DIR}/${FLAVOR}/awesomium-1.6.6 CACHE STRING "awesomium path")
SET(DEP_AWESOMIUM ${DEPS_DIR}/${FLAVOR}/awesomium-1.7-rc3 CACHE STRING "awesomium path")
SET(DEP_VLC ${DEPS_DIR}/${FLAVOR}/VLC-2.0.4 CACHE STRING "vlc path")
SET(DEP_ATB ${DEPS_DIR}/${FLAVOR}/AntTweakBar-1.15 CACHE STRING "AntTweakBar path")
SET(DEP_FREENECT ${DEPS_DIR}/${FLAVOR}/libfreenect-2013.01.13 CACHE STRING "freenect path")
SET(DEP_KINECT ${DEPS_DIR}/${FLAVOR}/KinectSDK-1.6 CACHE STRING "Kinect SDK path")

SET(DEP_GL "" CACHE STRING "GL path")
SET(DEP_IM ${DEPS_DIR}/${FLAVOR}/IM-3.8_vc9_lib CACHE STRING "im path")
SET(DEP_CD ${DEPS_DIR}/${FLAVOR}/CD-5.5.1_vc9_lib CACHE STRING "cd path")
SET(DEP_IUP ${DEPS_DIR}/${FLAVOR}/IUP-3.6_vc9_lib CACHE STRING "iup path")
SET(DEP_SDL ${DEPS_DIR}/${FLAVOR}/SDL-1.2.15 CACHE STRING "SDL path")
SET(DEP_SPICE ${DEPS_DIR}/${FLAVOR}/CSpice-N0064 CACHE STRING "cspice path")

SET(LUA "W:/Cloud/Dev/Deps/win32/LuaJIT-2.0.0-beta9/bin/luajit.exe" CACHE STRING "Lua executable")
SET(LUAC "W:/Cloud/Dev/Tools/win32/lua-5.1.4/luac5.1.exe" CACHE STRING "Luac executable")
SET(BIN2C_LUA "W:/Cloud/Dev/Tools/win32/lua-5.1.4/bin2c.lua" CACHE STRING "bin2c lua script")
SET(BIN2C "W:/Cloud/Dev/Tools/win32/lua-5.1.4/bin2c5.1.exe" CACHE STRING "bin2c executable")

SET(UPX "W:/Cloud/Dev/Tools/win32/upx-3.08/upx.exe" CACHE STRING "UPX executable")
