
class HWND {
};

namespace osg {

class Referenced {
};

class Image {
};

class Texture2D {
};

class State {
};

};

namespace Awesomium {

typedef HWND NativeWindow;

};

namespace KeyCodes {
  
  enum KeyCodes {
    AK_BACK,
    AK_TAB,
    AK_CLEAR,
    AK_RETURN,
    AK_SHIFT,
    AK_CONTROL,
    AK_MENU,
    AK_PAUSE,
    AK_CAPITAL,
    AK_KANA,AK_HANGUL,
    AK_JUNJA,
    AK_FINAL,
    AK_HANJA,
    AK_KANJI,
    AK_ESCAPE,
    AK_CONVERT,
    AK_NONCONVERT,
    AK_ACCEPT,
    AK_MODECHANGE,
    AK_SPACE,
    AK_PRIOR,
    AK_NEXT,
    AK_END,
    AK_HOME,
    AK_LEFT,
    AK_UP,
    AK_RIGHT,
    AK_DOWN,
    AK_SELECT,
    AK_PRINT,
    AK_EXECUTE,
    AK_SNAPSHOT,
    AK_INSERT,
    AK_DELETE,
    AK_HELP,
    AK_0,
    AK_1,
    AK_2,
    AK_3,
    AK_4,
    AK_5,
    AK_6,
    AK_7,
    AK_8,
    AK_9,
    AK_A,
    AK_B,
    AK_C,
    AK_D,
    AK_E,
    AK_F,
    AK_G,
    AK_H,
    AK_I,
    AK_J,
    AK_K,
    AK_L,
    AK_M,
    AK_N,
    AK_O,
    AK_P,
    AK_Q,
    AK_R,
    AK_S,
    AK_T,
    AK_U,
    AK_V,
    AK_W,
    AK_X,
    AK_Y,
    AK_Z,
    AK_LWIN,
    AK_RWIN,
    AK_APPS,
    AK_SLEEP,
    AK_NUMPAD0,
    AK_NUMPAD1,
    AK_NUMPAD2,
    AK_NUMPAD3,
    AK_NUMPAD4,
    AK_NUMPAD5,
    AK_NUMPAD6,
    AK_NUMPAD7,
    AK_NUMPAD8,
    AK_NUMPAD9,
    AK_MULTIPLY,
    AK_ADD,
    AK_SEPARATOR,
    AK_SUBTRACT,
    AK_DECIMAL,
    AK_DIVIDE,
    AK_F1,
    AK_F2,
    AK_F3,
    AK_F4,
    AK_F5,
    AK_F6,
    AK_F7,
    AK_F8,
    AK_F9,
    AK_F10,
    AK_F11,
    AK_F12,
    AK_F13,
    AK_F14,
    AK_F15,
    AK_F16,
    AK_F17,
    AK_F18,
    AK_F19,
    AK_F20,
    AK_F21,
    AK_F22,
    AK_F23,
    AK_F24,
    AK_NUMLOCK,
    AK_SCROLL,
    AK_LSHIFT,
    AK_RSHIFT,
    AK_LCONTROL,
    AK_RCONTROL,
    AK_LMENU,
    AK_RMENU,
    AK_BROWSER_BACK,
    AK_BROWSER_FORWARD,
    AK_BROWSER_REFRESH,
    AK_BROWSER_STOP,
    AK_BROWSER_SEARCH,
    AK_BROWSER_FAVORITES,
    AK_BROWSER_HOME,
    AK_VOLUME_MUTE,
    AK_VOLUME_DOWN,
    AK_VOLUME_UP,
    AK_MEDIA_NEXT_TRACK,
    AK_MEDIA_PREV_TRACK,
    AK_MEDIA_STOP,
    AK_MEDIA_PLAY_PAUSE,
    AK_MEDIA_LAUNCH_MAIL,
    AK_MEDIA_LAUNCH_MEDIA_SELECT,
    AK_MEDIA_LAUNCH_APP1,
    AK_MEDIA_LAUNCH_APP2,
    AK_OEM_1,
    AK_OEM_PLUS,
    AK_OEM_COMMA,
    AK_OEM_MINUS,
    AK_OEM_PERIOD,
    AK_OEM_2,
    AK_OEM_3,
    AK_OEM_4,
    AK_OEM_5,
    AK_OEM_6,
    AK_OEM_7,
    AK_OEM_8,
    AK_OEM_102,
    AK_PROCESSKEY,
    AK_PACKET,
    AK_ATTN,
    AK_CRSEL,
    AK_EXSEL,
    AK_EREOF,
    AK_PLAY,
    AK_ZOOM,
	AK_NONAME,
    AK_PA1,
    AK_OEM_CLEAR,AK_UNKNOWN,
  }
}
